<Project Sdk="Godot.NET.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>StarSwarm</RootNamespace>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Project\Common\" />
    <Folder Include="Project\Main\" />
    <Folder Include="Project\UI\MainScreen\" />
  </ItemGroup>
</Project>